### ISSUE TITLE
Sorry, I have a short question

### ISSUE THREAD

**Issue by ghost** [OpenMLTD/PlatinumTheater#1]
Hi, I have a short question about your tool so I'm leaving it here

Is there a tool for extracting the beat map of MLTD?
I want to visualize the beat map into a single long image, so human-readable text or bytes data with table information will be enough information I need

Actually I even don't know which asset stores the beat map information in tons of available assets...
I can see your projects are really wonderful! But it's too hard to figure out the input, or usage of each tool in your project, for the newbs like me.

Can I get any help with this?

Sorry for opening the meaningless issue

**Comment by hozuki** [comment]
Well there are some tools that can do this, but they are integrated parts of other apps. Currently there is no tool which only does parsing the beatmaps.

Beatmaps are in `scrobj_***.unity3d`, where `***` is the code name for its song (usually some kind of abbreviation). You can use [AssetStudio](https://github.com/Perfare/AssetStudio) to explore them. In each file there is an asset named `***_fumen` ("beatmap for ***"). You can see the asset contents (in human-readable form; stored in binary though) quite clear in AssetStudio.

To get started, you can have a look at:

- [ScrObjAnalyzer](https://github.com/thiEFcat/ScrObjAnalyzer), which parses exported JSON-like TXT files (provided by whom?) and convert to beatmaps for Tempest Wave.
- [MLTD beatmap support for TD simulator](https://github.com/hozuki/TheaterDaysSim/tree/master/src/plugins/StandardScoreFormats.Mltd), which reads `scrobj_***.unity3d` files and converts to internal format (to do the simulation).

I know, it's very boring to read complicated code when you don't know what to expect at first. The links are just for reference. You may come up with a more brilliant idea.

About handling a beatmap. MLTD beatmap's timing design is similar to [MIDI](http://midi.teragonaudio.com/tech/midifile/time.htm). That is, there is a global clock whose speed is variant; time units are in ticks (absolute); you need to compute the real time unit (e.g. seconds) from ticks according to current clock speed. An example is [here](https://github.com/hozuki/TheaterDaysSim/blob/master/src/TheaterDays.Scores/ScoreCompileHelper.cs) and [here](https://github.com/hozuki/TheaterDaysSim/blob/master/src/TheaterDays.Scores/ScoreCompileHelper.cs).

**Comment by ghost** [comment]
Thank you so much for your help! I surprised because I didn't expect for the very detailed information 😮 

The `.txt` file mentioned in `ScrObjAnalyzer` seems to be the `***_fumen_sobj` exported from `AssetStudio`, didn't check yet because I don't have the environment for building .NET applications. I'm a python newbie 😅 But the source code of that project is helpful.

Also, thanks for sharing your simulator project, source code for reading score format really helped me to figure out the usage of each data!

Thank You! 😊

**Comment by hozuki** [comment]
I think the text files are exported with [mikunyan](https://github.com/Ishotihadus/mikunyan).

Anyway, you can first try to parse text files (in AssetStudio's display format, or mikunyan's JSON) in Python. That will be a lot easier, but you have to integrate text file exporting yourself.
As for Unity asset reader in Python... there is [UnityPack](https://github.com/HearthSim/UnityPack) but I don't know how much support it can provide. The tool is still useful if you want to complete the task in Python though.

**Comment by ghost** [comment]
Hello Brother, I really appreciate for your previous help.
But I've got another question about the asset of MLTD, so leaving it here because I thought it will be better than creating a new issue 🤔 

I want to get the information about the cards from assets, such as their card name, name of voice asset, stats, skills, etc. I tried to look through many assets that have the name related to IDs of card (like 000tag000) but failed to get one.
What I want to know is which asset contains the information for the cards in the game. Are they stored as some special format?

Thanks for reading, and Sorry for making inconvenience again 😢

**Comment by hozuki** [comment]
Hmm, I don't know either. Texts should be stored locally (those `gtx` files) but I think the other information (stats, asset mapping, etc.) are pulled from the server when you start the game.

**Comment by ghost** [comment]
Yes, you were right! Just noticed that there is 'GetIdolDetailList' request when entering the idol profile pages. I'm curious why I didn't find it before asking you 😅 
Thank you for your help again!

===Edited===

Now I can see some assets that seem to be storing the texts (`.gtx`, is this BNEI's own asset extension?), but they give me the `.bytes` data which is not readable by the human. Seems they are binary data for the Unity, but cannot figure out the way to make them human-readable. Any suggestions for this?
